preferences:
  autowire-on-sync-mode: UPDATE_OPTIONAL_DEPENDENCIES
  repositories-mode: FAIL_ON_PROJECT_REPOS

repositories:
  gradle-plugin-portal:
    scope: PLUGINS
  google:
  maven-central:
  jit-pack:
  sonatype-oss-releases:
  rovo89-xposed-api:
    scope: LIBRARIES
    url: https://api.xposed.info/
    content:
      include:
        group: de.robv.android.xposed

plugins:
  com.android.application:
    alias: android-application
    version: 8.13.0
  org.jetbrains.kotlin.android:
    alias: kotlin-android
    version: 2.2.20
  com.google.devtools.ksp:
    alias: kotlin-ksp
    version: 2.2.20-2.0.2
  org.jetbrains.kotlin.plugin.compose:
    alias: kotlin-compose
    version: 2.2.20
  com.google.protobuf:
    alias: google-protobuf
    version: 0.9.5

libraries:
  de.robv.android.xposed:
    api:
      version: 82
      repositories: rovo89-xposed-api
  com.highcapable.yukihookapi:
    api:
      version: 1.3.1
    ksp-xposed:
      version-ref: <this>::api
  com.highcapable.kavaref:
    kavaref-core:
      version: 1.0.2
    kavaref-extension:
      version: 1.0.1

  com.highcapable.betterandroid:
    system-extension:
      version: 1.0.3

  androidx.lifecycle:
    lifecycle-runtime-ktx:
      version: 2.9.4
    lifecycle-viewmodel-ktx:
      version: 2.9.4

  androidx.core:
    core-ktx:
      version: 1.17.0
  androidx.activity:
    activity-compose:
      version: 1.10.1
  androidx.navigation:
    navigation-compose:
      version: 2.9.3

  androidx.compose.runtime:
    runtime:
      version: 1.9.3
  androidx.compose.ui:
    ui:
      version: 1.9.3
    ui-graphics:
      version: 1.9.3
    ui-tooling:
      version: 1.9.3
    ui-tooling-preview:
      version: 1.9.3
    ui-test-manifest:
      version: 1.9.3
    ui-test-junit4:
      version: 1.9.3


  androidx.compose.material3:
    material3:
      version: 1.4.0
  androidx.compose.material:
    material-icons-core:
      version: 1.7.8
    material-icons-extended:
      version: 1.7.8

  androidx.compose.animation:
    animation:
      version: 1.9.3
    animation-core:
      version: 1.9.3
    animation-graphics:
      version: 1.9.3

  com.google.protobuf:
    protoc:
      version: 4.32.1
    protobuf-kotlin:
      version: 4.32.1

  com.squareup.okhttp3:
    okhttp:
      version: 5.2.1
    logging-interceptor:
      version: 5.2.1
  com.google.code.gson:
    gson:
      version: 2.13.2
  
  androidx.datastore:
    datastore:
      version: 1.1.7
  
  androidx.test.ext:
    junit:
      version: 1.3.0
  androidx.test.espresso:
    espresso-core:
      version: 3.7.0
  junit:
    junit:
      version: 4.13.2